# Generated by Django 4.0.5 on 2022-06-05 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_profile_followers_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deslikes',
            field=models.ManyToManyField(blank=True, related_name='deslikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
